"""Shared configuration models, event records, and lightweight utilities."""

from supercharged_coral.common.config import (
    CAMERA_SOURCE_TYPES,
    DEFAULT_OBJECT_CLASSES,
    MOTION_ALGORITHMS,
    CameraConfig,
    MotionConfig,
    PlatformConfig,
    camera_config_from_mapping,
    load_config,
    motion_config_from_mapping,
    platform_config_from_mapping,
)
from supercharged_coral.common.events import (
    DatasetVersion,
    DeploymentRecord,
    Detection,
    EvaluationReport,
    Frame,
    HardwareHealth,
    ModelArtifact,
    MotionRegion,
    MotionResult,
    QualityResult,
    Region,
    TeacherOutput,
    Track,
    TrainingRequest,
    utc_now,
)

__all__ = [
    "CAMERA_SOURCE_TYPES",
    "CameraConfig",
    "DatasetVersion",
    "DEFAULT_OBJECT_CLASSES",
    "DeploymentRecord",
    "Detection",
    "EvaluationReport",
    "Frame",
    "HardwareHealth",
    "MOTION_ALGORITHMS",
    "ModelArtifact",
    "MotionConfig",
    "MotionRegion",
    "MotionResult",
    "PlatformConfig",
    "QualityResult",
    "Region",
    "TeacherOutput",
    "Track",
    "TrainingRequest",
    "camera_config_from_mapping",
    "load_config",
    "motion_config_from_mapping",
    "platform_config_from_mapping",
    "utc_now",
]
